name: elibrary_printing
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  equatable: ^2.0.5
  intl: ^0.19.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.20
  file_picker: ^6.2.0
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true
